name: Publish to pypi

on:
  workflow_run:
    workflows: ['Unit tests']
    types:
      - completed

jobs:
  build-and-deploy:
    runs-on: ubuntu-lastest
    environment:
      name: pypi
      url: https://pypi.org/p/g-robotframework
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup Python 3.10 Environment
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: 'Build'
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Publish package to PyPi
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true
        user: __token__
        password: ${{ secrets.API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/